import { useEffect, useState } from "react";

/**
 * MarketNarrator — plain-English market summary generated by a local LLM
 * on a timer (see backend/narrator.py). Shows the latest narration plus
 * how long ago it was generated.
 */
export default function MarketNarrator({ narration }) {
  const [, forceTick] = useState(0);

  // Re-render once a second so the "Xs ago" label stays live.
  useEffect(() => {
    const id = setInterval(() => forceTick((n) => n + 1), 1000);
    return () => clearInterval(id);
  }, []);

  if (!narration) {
    return (
      <div className="narrator-panel narrator-panel--empty">
        <span className="narrator-badge">SUMMARY</span>
        <span className="narrator-text narrator-text--muted">Waiting for first market summary...</span>
      </div>
    );
  }

  const secondsAgo = Math.max(0, Math.round((Date.now() - narration.ts) / 1000));

  return (
    <div className="narrator-panel">
      <span className="narrator-badge">SUMMARY</span>
      <span className="narrator-text">{narration.text}</span>
      <span className="narrator-age">{secondsAgo}s ago</span>
    </div>
  );
}
